### ISSUE TITLE
ADD maxwell  gen1 NV110 (nv117, ...)

### ISSUE THREAD

**Issue by ghost** [imirkin/re-vp2#1]
VP6 chip is not supported, need to add Maxwell gen1 GTX 750/750 ti with nvidia-340.XX driver

**Comment by imirkin** [comment]
VP6 isn't just not supported by extract_firmware.py. It's also entirely unsupported by nouveau kernel or mesa. We don't know what form the firmware takes, how much of it there is, etc. Once we do, happy to add it here.
